version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Miami
    volumes:
      - /path/to/data:/config
      - /path/to/movies:/movies
      - /path/to/downloadclient-downloads:/downloads
    ports:
      - 7878:7878 #webui
    restart: unless-stopped
  qbt:
        image: lscr.io/linuxserver/qbittorrent
        container_name: qbittorrent
        environment:
          - PGID=1000
          - PUID=1000
          - TZ=America/Miami
        volumes:
          - /path/to/downloadclient-downloads:/downloads
          - /path/to/data:/config
        ports:
          - 8080:8080 #webui
          - 11223:11223 #public-port
    restart: unless-stopped
  jackett:
        image: lscr.io/linuxserver/jackett
        container_name: jackett
        environment:
          - PGID=1000
          - PUID=1000
          - TZ=America/Miami
        volumes:
          - /path/to/data:/config
          - /path/to/downloadclient-downloads:/downloads
